### ISSUE TITLE
Documentation of the command-line tool could be improved

### ISSUE THREAD

**Issue by bortzmeyer** [keltia/ripe-atlas#6]
A first example (but there are many others):

```
% ./atlas -h
...
   --format value, -f value      specify output format
```

What are the possible values for the format? ` ./atlas --format foobar` does not even send back an error message. (Reading the source, I have the feeling the option is ignored...)

Second example, I want to increase the number of probes in a measurement I create. I have no idea how to do it. Am I supposed to use the mysterious ` --fields ` ?

**Comment by keltia** [comment]
`--format` is currently unused, idea is to generate XML or YAML output at some point.

Most of the options reflect the API itself, not everything is yet implemented.  For the number of probes, until I implement that option, I'd suggest editing the configuration file.

**Comment by keltia** [comment]
I have marked `--format` as "NOT IMPLEMENTED" for now.

**Comment by bortzmeyer** [comment]
But the configuration file itself does not seem to be documented.

**Comment by keltia** [comment]
I'm working on that, README.md on `develop` now has a bit more information.

**Comment by keltia** [comment]
Release 0.22 has been merged into master/develop.  Keeping the ticket for reference.

**Comment by bortzmeyer** [comment]
It is not obvious (without looking at the source code) to see what's must be modified in the configuration file to request for more probes.

**Comment by keltia** [comment]
I'm working in a branch to make this work.  There will be a change in the configuration file:
```
# Default configuration file
API_key = "<INSERT-API-KEY>"
default_probe = 666

[probe_set]
pool_size = 10
type = "area"
value = "WW"
```
and I have new options to override the configuration values from the CLI:
```
   --pool-size value             Number of probes to request (default: 0)
   --area-type value             Set type for probes (area, country, etc.)
   --area-value value            Value for the probe set (WW, West, etc.)
```
Would it be more satisfactory?

**Comment by keltia** [comment]
Please see release 0.23.
